# Generated by Django 5.2.6 on 2025-09-30 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Pregunta')),
                ('answer', models.TextField(help_text='Permite HTML seguro (párrafos, listas, enlaces)', verbose_name='Respuesta')),
                ('category', models.CharField(blank=True, max_length=80, null=True, verbose_name='Categoría')),
                ('slug', models.SlugField(blank=True, help_text='Se autogenera a partir de la pregunta', unique=True)),
                ('published', models.BooleanField(default=True, verbose_name='Publicado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['-updated_at'],
            },
        ),
    ]
